all: clean links

clean:
	rm -f b.py b.txt
	rm -f c0.py c6.py c8.py co.py ct.py
	rm -f dis.py
	rm -f g.py
	rm -f j.py jc.py
	rm -f m md.py
	rm -f o.py
	rm -f p.py p0.py pa.py pc.py pi.py pk.py pr.py
	rm -f s.txt
	rm -f u.py
	rm -f x1.py x2.py xi.py xm.py xm0.py xy.py
	rm -f z.py

links:
	ln -s ../.gem/ByteCode.py                   b.py
	ln -s boot.txt                              b.txt
	ln -s ../.gem/Code.py                       co.py
	ln -s ../.gem/c0.py                         c0.py
	ln -s ../.gem/C_Types.py                    ct.py
	ln -s /usr/lib/python2.6/ctypes/__init__.py c6.py
	ln -s ../.gem/Ctypes8.py                    c8.py
	ln -s /usr/lib/python2.6/dis.py             dis.py
	ln -s ../Junk/Junk.py                       j.py
	ln -s ../Junk/Code.py                       jc.py
	ln -s ../.gem/Gem.py                        g.py
	ln -s Makefile                              m
	ln -s ../.gem/MemberDescriptor.py           md.py
	ln -s /usr/lib/python2.6/opcode.py          o.py
	ln -s ../.gem/Parser.py                     p.py
	ln -s ../Pattern/sre_constants.py           p0.py
	ln -s ../Pattern/sre_parse.py               pa.py
	ln -s ../Pattern/__init__.py                pi.py
	ln -s ../Pattern/sre_compile.py             pc.py
	ln -s ../.gem/Pack.py                       pk.py
	ln -s ../Pattern/re.py                      pr.py
	ln -s /home/joy/misc/spades.txt             s.txt
	ln -s ../.gem/UseCtypes.py                  u.py
	ln -s ../pyxie                              x1.py
	ln -s ../.gem/Pyxie.py                      x2.py
	ln -s ../Pyxie/__init__.py                  xi.py       #   Unused
	ln -s ../Pyxie/Main.py                      xm0.py      #   Unused
	ln -s ../Pyxie/Main2.py                     xm.py       #   Unused
	ln -s ../.gem/xyz.py                        xy.py
	ln -s ../.gem/Tokenizer.py                  z.py
